// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'spacer_builder.dart';

// **************************************************************************
// Generator: JsonWidgetLibraryBuilder
// **************************************************************************

// ignore_for_file: avoid_init_to_null
// ignore_for_file: deprecated_member_use

// ignore_for_file: prefer_const_constructors
// ignore_for_file: prefer_const_constructors_in_immutables
// ignore_for_file: prefer_final_locals
// ignore_for_file: prefer_if_null_operators
// ignore_for_file: prefer_single_quotes
// ignore_for_file: unused_local_variable

class SpacerBuilder extends _SpacerBuilder {
  const SpacerBuilder({required super.args});

  static const kType = 'spacer';

  /// Constant that can be referenced for the builder's type.
  @override
  String get type => kType;

  /// Static function that is capable of decoding the widget from a dynamic JSON
  /// or YAML set of values.
  static SpacerBuilder fromDynamic(
    dynamic map, {
    JsonWidgetRegistry? registry,
  }) =>
      SpacerBuilder(
        args: map,
      );

  @override
  SpacerBuilderModel createModel({
    ChildWidgetBuilder? childBuilder,
    required JsonWidgetData data,
  }) {
    final model = SpacerBuilderModel.fromDynamic(
      args,
      registry: data.jsonWidgetRegistry,
    );

    return model;
  }

  @override
  Spacer buildCustom({
    ChildWidgetBuilder? childBuilder,
    required BuildContext context,
    required JsonWidgetData data,
    Key? key,
  }) {
    final model = createModel(
      childBuilder: childBuilder,
      data: data,
    );

    return Spacer(
      flex: model.flex,
      key: key,
    );
  }
}

class JsonSpacer extends JsonWidgetData {
  JsonSpacer({
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
    this.flex = 1,
  }) : super(
          jsonWidgetArgs: SpacerBuilderModel.fromDynamic(
            {
              'flex': flex,
              ...args,
            },
            args: args,
            registry: registry,
          ),
          jsonWidgetBuilder: () => SpacerBuilder(
            args: SpacerBuilderModel.fromDynamic(
              {
                'flex': flex,
                ...args,
              },
              args: args,
              registry: registry,
            ),
          ),
          jsonWidgetType: SpacerBuilder.kType,
        );

  /* AUTOGENERATED FROM [Spacer.flex]*/
  /// The flex factor to use in determining how much space to take up.
  ///
  /// The amount of space the [Spacer] can occupy in the main axis is determined
  /// by dividing the free space proportionately, after placing the inflexible
  /// children, according to the flex factors of the flexible children.
  ///
  /// Defaults to one.
  final int flex;
}

/* AUTOGENERATED FROM [Spacer]*/
/// Creates a flexible space to insert into a [Flexible] widget.
///
/// The [flex] parameter may not be null or less than one.
class SpacerBuilderModel extends JsonWidgetBuilderModel {
  const SpacerBuilderModel(
    super.args, {
    this.flex = 1,
  });

  /* AUTOGENERATED FROM [Spacer.flex]*/
  /// The flex factor to use in determining how much space to take up.
  ///
  /// The amount of space the [Spacer] can occupy in the main axis is determined
  /// by dividing the free space proportionately, after placing the inflexible
  /// children, according to the flex factors of the flexible children.
  ///
  /// Defaults to one.
  final int flex;

  static SpacerBuilderModel fromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    final result = maybeFromDynamic(
      map,
      args: args,
      registry: registry,
    );

    if (result == null) {
      throw Exception(
        '[SpacerBuilder]: requested to parse from dynamic, but the input is null.',
      );
    }

    return result;
  }

  static SpacerBuilderModel? maybeFromDynamic(
    dynamic map, {
    Map<String, dynamic> args = const {},
    JsonWidgetRegistry? registry,
  }) {
    SpacerBuilderModel? result;

    if (map != null) {
      if (map is String) {
        map = yaon.parse(
          map,
          normalize: true,
        );
      }

      if (map is SpacerBuilderModel) {
        result = map;
      } else {
        registry ??= JsonWidgetRegistry.instance;
        map = registry.processArgs(map, <String>{}).value;
        result = SpacerBuilderModel(
          args,
          flex: () {
            dynamic parsed = JsonClass.maybeParseInt(map['flex']);

            parsed ??= 1;

            return parsed;
          }(),
        );
      }
    }

    return result;
  }

  @override
  Map<String, dynamic> toJson() {
    return JsonClass.removeNull({
      'flex': 1 == flex ? null : flex,
      ...args,
    });
  }
}

class SpacerSchema {
  static const id =
      'https://peiffer-innovations.github.io/flutter_json_schemas/schemas/burgan_ui/spacer.json';

  static final schema = <String, Object>{
    r'$schema': 'http://json-schema.org/draft-07/schema#',
    r'$id': id,
    'title': 'Spacer',
    'type': 'object',
    'additionalProperties': false,
    'properties': {
      'flex': SchemaHelper.numberSchema,
    },
  };
}
