clone:
  depth: 2
definitions:
  steps:
    - step: &set-environment-variables
        name: Set Environment Variables
        clone:
          enabled: false
        runs-on:
          - macos
          - flutter
        script:
          - printenv | xargs echo export > .envs
        artifacts:
          download: false # do not download artifacts in this step
          paths:
            - .envs
    - step: &copy-scripts
        name: Copy Scripts
        clone:
          enabled: false
        runs-on:
          - macos
          - flutter
        script:
          - >-
            cp ~/jenkins/helpers/build_flutter.sh .
        artifacts:
          download: false # do not download artifacts in this step
          paths: # defining artifacts to be passed to each future step
            - build_flutter.sh

    - step: &flutter-pub-get
        name: Flutter Pub Get
        runs-on:
          - macos
          - flutter
        script:
          - flutter clean
          - flutter pub get
        artifacts:
          - .dart_tool/**
          - .flutter-plugins
          - .flutter-plugins-dependencies
          - build/**
        caches:
          - dartpubcache

    - step: &flutter-lint
        name: Flutter Lint and Test
        runs-on:
          - macos
          - flutter
        caches:
          - dartpubcache
        script:
          - flutter analyze --no-fatal-infos --no-fatal-warnings

    - step: &flutter-build-android
        name: Flutter Build Android
        runs-on:
          - macos
          - flutter
        script:
          - source .envs
          - ./build_flutter.sh android -t $FLUTTER_TARGET
        artifacts:
          - android/**
          - build/**
        caches:
          - dartpubcache

    - step: &run-sonar-test
        name: Run Sonar Test
        runs-on:
          - macos
          - flutter
        artifacts:
          - tests.output
        script:
          - flutter test --machine --coverage > tests.output
          # - sonar-scanner


  caches:
    dartpubcache: $HOME/.pub-cache

pipelines:
  branches:
    main:
      - step: *copy-scripts
      - step: *flutter-pub-get
      - step: *flutter-lint
      - step: *run-sonar-test
      - step: *set-environment-variables
      - step: *flutter-build-android

    feature/*:
      - step: *copy-scripts
      - step: *flutter-pub-get
      - step: *flutter-lint
      - step: *run-sonar-test
      - step: *set-environment-variables
      - step: *flutter-build-android

    release/*:
      - step: *copy-scripts
      - step: *flutter-pub-get
      - step: *flutter-lint
      - step: *run-sonar-test
      - step: *set-environment-variables
      - step: *flutter-build-android

    test/*:
      - step: *copy-scripts
      - step: *flutter-pub-get
      - step: *flutter-lint
      - step: *run-sonar-test
      - step: *set-environment-variables
      - step: *flutter-build-android

  pull-requests:
    'feature/*':
      - step: *copy-scripts
      - step: *flutter-pub-get
      - step: *flutter-lint
      - step: *run-sonar-test
      - step: *set-environment-variables
      - step: *flutter-build-android
