name: burgan_ui
description: Burgan Flutter UI Project
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Related
  flutter_svg: ^2.0.5
  cupertino_icons: ^1.0.2

  # Dynamic Widget Building
  json_dynamic_widget: # DO NOT SET. It's coming from burgan_core project
  child_builder: # DO NOT SET. It's coming from burgan_core project

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
