name: burgan_ui
description: Burgan Flutter UI Project
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI Related
  flutter_svg: ^2.0.7
  cupertino_icons: ^1.0.2

  # Core
  burgan_core:
    git:
      url: git@github.com:amorphie/flutter.core.git
      ref: 0.0.6

  # Dynamic Widget Building
  json_dynamic_widget: ^6.1.2+1
  child_builder: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
